"""Part 16: the Core Freeze V1 manifest verifies, and its verifier can fail.

The first test is the one that matters day to day: the checked-out tree IS
Core Freeze V1, or a descendant that kept its contract. Everything after it is
about the verifier rather than the tree -- each takes the real stored manifest,
breaks exactly one fact in a copy, and requires the verifier to fail on the
check that owns that fact. A verifier that passed every one of these copies
would be a verifier that compares nothing.

The tampered copies are held in memory. Nothing here writes to the manifest.
"""

from __future__ import annotations

import copy
import json
import pathlib
import subprocess
import sys

import pytest

REPO = pathlib.Path(__file__).resolve().parents[1]
MANIFEST = REPO / "certification" / "core_freeze_v1.json"

pytestmark = pytest.mark.skipif(
    not (REPO / ".git").exists(), reason="the freeze verifier reads git state"
)

from tools.certification import core_freeze, core_freeze_v3  # noqa: E402


@pytest.fixture(scope="module")
def live():
    return core_freeze.collect_live(REPO)


@pytest.fixture(scope="module")
def manifest():
    assert MANIFEST.exists(), "certification/core_freeze_v1.json is missing"
    return json.loads(MANIFEST.read_bytes())


def failing(result) -> set[str]:
    return set(result.failed())


# =====================================================================
# the tree
# =====================================================================

#: The V1 checks Core Freeze V4 supersedes, each with the reason, and NOTHING else may fail.
#:
#: AMENDED at Core Freeze V4 (I-29, R-65). `contract.api` compares the LIVE frozen digest with the
#: one V1 recorded, and the 2026-09-16 scientific core re-audit moved it additively (`c80e6418` ->
#: `f18aa806`, the same 194 symbols). `contract.serialization` compares the live serialization facts
#: with V1's, and this round bumped eight record schemas CONDITIONALLY -- a record that carries a new
#: binding declares a new version and an old record keeps its bytes -- so V1's recorded
#: `accepted_versions` lists are now prefixes of the live ones. Both are superseded by V4, which
#: proves the supersession additive difference by difference against the bytes V1 committed; neither
#: is softened here, they are NAMED, and the assertion below requires V4's proof to hold.
SUPERSEDED_BY_V4 = {
    "contract.api": "the frozen digest moved additively; core_freeze_v4.additive_only_problems is empty",
    "contract.serialization": "eight conditional schema bumps; every V1 version is still accepted",
    "bytes.pinned_contract_files": (
        "the two API snapshot files are re-pinned by V4. V1's pin is still checkable and is still "
        "checked: core_freeze_v4.stored_v1_frozen_snapshot reads the file OUT OF GIT at the V1 "
        "baseline commit and refuses it unless its bytes hash to the digest V1's own manifest "
        "recorded -- which is where the additive comparison starts"),
    "certificate.verifies": "the certificate is regenerated by the certificate-only child",
}


def test_the_tree_is_core_freeze_v1(live):
    """Deliberately not softened on a dirty tree, like the certificate's test."""
    result = core_freeze.verify(REPO, live=live)
    unexpected = failing(result) - set(SUPERSEDED_BY_V4)
    assert not unexpected, "\n" + result.render()
    if failing(result):
        # A superseded check may only fail while V4 PROVES the supersession. Without this the three
        # names above would be an allow-list, which is the shape this whole round exists to remove.
        from tools.certification import core_freeze_v4

        stored = core_freeze_v4.stored_v1_frozen_snapshot(REPO)
        from engcore import api_snapshot

        assert core_freeze_v4.additive_only_problems(
            stored["snapshot"], api_snapshot.frozen_only()) == []
        assert api_snapshot.frozen_only()["symbol_count"] == 194
        assert stored["file_sha256"] == json.loads(MANIFEST.read_bytes())["api"]["pinned_files"][
            core_freeze_v4.V1_FROZEN_SNAPSHOT_FILE]


def test_the_tree_is_the_exact_freeze_or_a_contract_keeping_descendant(live, manifest):
    result = core_freeze.verify_manifest(manifest, live, require_clean=False)
    assert result.mode in ("EXACT_FREEZE", "DESCENDANT"), result.mode


def test_the_command_line_verifier_agrees_with_the_function(live):
    """`python -m tools.certification.core_freeze --verify` is the Part 16 command."""
    proc = subprocess.run(
        [sys.executable, "-X", "utf8", "-m", "tools.certification.core_freeze",
         "--verify"],
        cwd=REPO, capture_output=True, text=True, encoding="utf-8",
    )
    expected = core_freeze.verify(REPO, live=live).ok
    assert (proc.returncode == 0) == expected, proc.stdout[-2000:] + proc.stderr[-2000:]
    assert proc.stdout.strip().splitlines()[-1] == ("OK" if expected else "FAILED")


# =====================================================================
# the frozen contract -- each fact, broken once
# =====================================================================

def test_a_changed_frozen_digest_fails(live, manifest):
    broken = copy.deepcopy(manifest)
    broken["api"]["frozen_digest"] = "0" * 64
    assert "contract.api" in failing(
        core_freeze.verify_manifest(broken, live, require_clean=False))


def test_silently_promoting_an_experimental_symbol_fails(live, manifest):
    """Part 5's forbidden move, done CONSISTENTLY so the internal checks pass.

    Dropping a symbol from the experimental list and raising the frozen count to
    match is exactly what a silent promotion looks like in a manifest someone
    edited carefully. The live facts must refuse it.
    """
    broken = copy.deepcopy(manifest)
    broken["api"]["experimental"] = broken["api"]["experimental"][1:]
    broken["api"]["experimental_count"] -= 1
    broken["api"]["frozen_count"] += 1
    broken["api"]["frozen_count_expected"] += 1
    failed = failing(core_freeze.verify_manifest(broken, live, require_clean=False))
    assert "contract.api" in failed
    assert "experimental.visibly_classified" in failed


def test_a_legacy_reader_losing_a_declared_version_fails(live, manifest):
    broken = copy.deepcopy(manifest)
    readers = broken["contract"]["facts"]["serialization"]["legacy_readers"]
    readers["ProvenanceRecord"]["accepted_versions"] = (
        readers["ProvenanceRecord"]["accepted_versions"][1:]
    )
    assert "contract.serialization" in failing(
        core_freeze.verify_manifest(broken, live, require_clean=False))


def test_a_changed_round_trip_inventory_fails(live, manifest):
    broken = copy.deepcopy(manifest)
    broken["contract"]["facts"]["serialization"]["round_trippable_count"] = 62
    assert "contract.serialization" in failing(
        core_freeze.verify_manifest(broken, live, require_clean=False))


def test_a_changed_material_digest_fails(live, manifest):
    """Digest SEMANTICS are frozen, so the reference digests are too."""
    broken = copy.deepcopy(manifest)
    broken["contract"]["facts"]["identity"]["reference"]["parameter"] = "f" * 64
    assert "contract.identity" in failing(
        core_freeze.verify_manifest(broken, live, require_clean=False))


def test_a_changed_failure_order_fails(live, manifest):
    broken = copy.deepcopy(manifest)
    order = broken["contract"]["facts"]["ordering"]["sequential"]["failure_order"]
    order.reverse()
    assert "contract.ordering" in failing(
        core_freeze.verify_manifest(broken, live, require_clean=False))


def test_a_new_exception_family_fails(live, manifest):
    broken = copy.deepcopy(manifest)
    broken["contract"]["facts"]["exceptions"]["roots"]["engcore.new.Root"] = 1
    assert "contract.exceptions" in failing(
        core_freeze.verify_manifest(broken, live, require_clean=False))


def test_an_internally_inconsistent_manifest_fails(live, manifest):
    broken = copy.deepcopy(manifest)
    broken["api"]["experimental_count"] = 10
    assert "manifest.internal_consistency" in failing(
        core_freeze.verify_manifest(broken, live, require_clean=False))


def test_a_changed_pinned_snapshot_file_fails(live, manifest):
    broken = copy.deepcopy(manifest)
    name = sorted(broken["api"]["pinned_files"])[0]
    broken["api"]["pinned_files"][name] = "0" * 64
    assert "bytes.pinned_contract_files" in failing(
        core_freeze.verify_manifest(broken, live, require_clean=False))


# =====================================================================
# exact freeze vs descendant
# =====================================================================

def test_a_descendant_that_keeps_the_contract_still_verifies(live, manifest):
    """The post-freeze policy made executable: `src/` may change, the contract may not.

    Simulated by changing the RECORDED src tree hash, which is what the verifier
    sees when a later commit refactors internals. The byte-level checks must
    become informational, and the contract checks must still bind and pass.

    This is also a certificate-child self-check. The same trusted check requires
    the full verifier of the binding freeze to pass against the freshly generated
    certificate. That was Core Freeze V2; since the main audit (2026-09-15) V2's
    serialization contract is superseded and Core Freeze V3 binds, so V3 cannot
    evade the certificate-child lifecycle either.
    """
    later = copy.deepcopy(manifest)
    later["trees"]["src"] = "0" * 40
    later["domain"]["digest"] = "0" * 64  # new domain work is allowed after a freeze
    result = core_freeze.verify_manifest(later, live, require_clean=False)
    assert result.mode == "DESCENDANT"
    # AMENDED at Core Freeze V4, as the first test in this file was and for the same reason: the
    # three checks V4 supersedes fail here too, because this copy tampers with the src tree hash
    # and not with the API or the serialization facts. Nothing else may fail, and the supersession
    # must be proved, which the first test does over the same tree.
    assert set(result.failed()) <= set(SUPERSEDED_BY_V4), "\n" + result.render()
    informational = {c.name for c in result.checks if not c.binding}
    assert {"domain.digest", "bytes.reproduction_sha256"} <= informational

    # AMENDED at Core Freeze V4 (I-29, R-65): V3 is the freeze this one descends FROM, and its own
    # identity references are refused by this tree exactly as V2's were by V3 -- which is the
    # supersession, measured. So the binding freeze the certificate child may not evade is V4, and
    # V4's verifier is the one required to pass here. V3's manifest stays byte-identical and is
    # recorded in V4's by digest.
    from tools.certification import core_freeze_v4

    v4_result = core_freeze_v4.verify(REPO, require_assurance=False)
    unexpected = {c.name for c in v4_result.checks if c.binding and not c.ok} - {
        "v1.freeze_verifies", "certificate.verifies", "certificate.covers_required_areas"}
    assert not unexpected, "\nCore Freeze V4:\n" + v4_result.render()
    assert core_freeze_v4.v3_fixtures_refused()["refused"], (
        "V3's identity references are accepted, so nothing supersedes V3 and this tree is a V3 tree")


def test_on_the_exact_freeze_the_domain_digest_binds(live, manifest):
    broken = copy.deepcopy(manifest)
    broken["domain"]["digest"] = "0" * 64
    result = core_freeze.verify_manifest(broken, live, require_clean=False)
    if result.mode != "EXACT_FREEZE":
        pytest.skip("this tree is a descendant; the domain digest is informational")
    assert "domain.digest" in failing(result)


def test_a_descendant_that_breaks_the_contract_fails(live, manifest):
    later = copy.deepcopy(manifest)
    later["trees"]["src"] = "0" * 40
    later["api"]["frozen_digest"] = "0" * 64
    result = core_freeze.verify_manifest(later, live, require_clean=False)
    assert result.mode == "DESCENDANT"
    assert "contract.api" in failing(result)


# =====================================================================
# the assurance record
# =====================================================================

def test_an_assurance_record_for_a_different_manifest_fails(live, manifest):
    result = core_freeze.verify_manifest(manifest, live, require_clean=False)
    core_freeze.verify_assurance(
        {"schema": core_freeze.ASSURANCE_SCHEMA, "manifest_sha256": "0" * 64,
         "tag": manifest["freeze"]["tag"], "candidate_commit": live.head,
         "evidence": {}, "results": {}},
        MANIFEST.read_bytes(), manifest, live, result, changed_paths=[],
    )
    assert "assurance.manifest_sha256" in failing(result)


def test_code_changed_after_the_assured_candidate_fails(live, manifest):
    """The property that makes the tagged src/ provably the assured src/."""
    exact = copy.deepcopy(manifest)
    exact["trees"] = dict(live.trees)  # force EXACT mode for this check
    result = core_freeze.verify_manifest(exact, live, require_clean=False)
    core_freeze.verify_assurance(
        {"schema": core_freeze.ASSURANCE_SCHEMA,
         "manifest_sha256": core_freeze.sha256_bytes(MANIFEST.read_bytes()),
         "tag": manifest["freeze"]["tag"], "candidate_commit": live.head,
         "evidence": {}, "results": {}},
        MANIFEST.read_bytes(), exact, live, result,
        changed_paths=["src/engcore/scientific/units/quantity.py"],
    )
    assert "assurance.post_candidate_changes_are_evidence_only" in failing(result)


def test_no_post_candidate_path_is_code_or_a_test():
    for path in core_freeze.POST_CANDIDATE_PATHS:
        assert not path.startswith(("src/", "tests/", "tools/")), path
        assert not path.endswith(".py"), path


# =====================================================================
# what the manifest says about itself
# =====================================================================

def test_the_manifest_records_the_blocked_candidate(manifest):
    blocked = manifest["freeze"]["blocked_candidates"]
    assert [b["commit"] for b in blocked] == [core_freeze.FINAL_FREEZE_BASELINE]
    assert blocked[0]["verdict"] == "FREEZE_BLOCKED"


def test_the_manifest_freezes_exactly_194_and_excludes_exactly_the_eleven(manifest):
    assert manifest["api"]["frozen_count"] == 194
    assert sorted(map(tuple, manifest["api"]["experimental"])) == sorted([
        ("engcore.inference", "FieldObservationError"),
        ("engcore.inference", "FieldObservationKind"),
        ("engcore.inference", "FieldObservationOperator"),
        ("engcore.studies", "TCR_MODEL_REF"),
        ("engcore.studies", "TcrTruth"),
        ("engcore.studies", "build_tcr_parameter_set"),
        ("engcore.studies", "ols_reference_estimate"),
        ("engcore.studies", "synthesize_tcr_observations"),
        ("engcore.studies", "tcr_forward_evaluator"),
        ("engcore.studies", "tcr_forward_table"),
        ("engcore.studies", "tcr_prediction"),
    ])


def test_the_manifest_states_its_non_claims(manifest):
    text = " ".join(manifest["non_claims"])
    for required in ("EXPERIMENTAL != FROZEN", "error prose", "EI/RI/FM/SP",
                     "seven exception roots", "unsupported checkout alias"):
        assert required in text, required


def test_the_manifest_carries_the_change_policy(manifest):
    policy = manifest["change_policy"]
    assert set(policy) == {
        "allowed_without_breaking_freeze",
        "requires_core_compatibility_review",
        "requires_new_core_freeze_version",
    }
    assert "silently promoting" in manifest["experimental_policy"]["forbidden"]


def test_every_reference_exists(manifest):
    missing = [
        ref["path"] for ref in manifest["references"].values()
        if not (REPO / ref["path"]).exists()
        and ref["path"] not in (core_freeze.ASSURANCE_PATH, core_freeze.REPORT_PATH)
    ]
    assert not missing, missing
