"""Domain-neutral multiphysics scientific contracts."""

from .conservation import (
    CONSERVATION_TERM_BINDING_SCHEMA,
    COUPLED_CONSERVATION_SCHEMA,
    BalanceSide,
    ConservationTermBinding,
    CoupledConservation,
    TransferMeasure,
)
from .frames import FRAME_TRANSFORM_SCHEMA, FrameTransform
from .graph import (
    COUPLING_EDGE_SCHEMA,
    PHYSICS_GRAPH_SCHEMA,
    CouplingEdge,
    PhysicsGraph,
    ReductionOperator,
)
from .mapping import (
    FIELD_MAPPING_SCHEMA,
    MAPPING_DIAGNOSTICS_SCHEMA,
    ExtrapolationPolicy,
    FieldMappingDefinition,
    FieldMappingMethod,
    MappingDiagnostics,
)
from .participant import PARTICIPANT_SCHEMA, ParticipantSpec
from .plan import (
    COUPLING_PLAN_SCHEMA,
    CONVERGENCE_CRITERION_SCHEMA,
    RELAXATION_POLICY_SCHEMA,
    TIME_POLICY_SCHEMA,
    ConvergenceCriterion,
    CouplingPlan,
    CouplingScheme,
    IterationSemantics,
    RelaxationKind,
    RelaxationPolicy,
    ResidualNorm,
    TimePolicy,
)
from .ports import (
    PORT_REF_SCHEMA,
    PORT_SCHEMA,
    FieldAlgebra,
    PortDefinition,
    PortDirection,
    PortKind,
    PortRef,
)
from .report import (
    EDGE_RESIDUAL_SCHEMA,
    ITERATION_SCHEMA,
    PARTICIPANT_STEP_SCHEMA,
    RUN_SCHEMA,
    WINDOW_SCHEMA,
    CouplingIterationRecord,
    CouplingWindowRecord,
    EdgeResidual,
    MultiphysicsRunRecord,
    ParticipantStepRecord,
    WindowOutcome,
)
from .state import CHECKPOINT_SCHEMA, CheckpointRecord

__all__ = [
    "CHECKPOINT_SCHEMA",
    "CONSERVATION_TERM_BINDING_SCHEMA",
    "COUPLED_CONSERVATION_SCHEMA",
    "COUPLING_EDGE_SCHEMA",
    "COUPLING_PLAN_SCHEMA",
    "CONVERGENCE_CRITERION_SCHEMA",
    "EDGE_RESIDUAL_SCHEMA",
    "FIELD_MAPPING_SCHEMA",
    "FRAME_TRANSFORM_SCHEMA",
    "ITERATION_SCHEMA",
    "MAPPING_DIAGNOSTICS_SCHEMA",
    "PARTICIPANT_SCHEMA",
    "PARTICIPANT_STEP_SCHEMA",
    "PHYSICS_GRAPH_SCHEMA",
    "PORT_REF_SCHEMA",
    "PORT_SCHEMA",
    "RELAXATION_POLICY_SCHEMA",
    "RUN_SCHEMA",
    "TIME_POLICY_SCHEMA",
    "WINDOW_SCHEMA",
    "BalanceSide",
    "CheckpointRecord",
    "ConservationTermBinding",
    "ConvergenceCriterion",
    "CoupledConservation",
    "CouplingEdge",
    "CouplingIterationRecord",
    "CouplingPlan",
    "CouplingScheme",
    "CouplingWindowRecord",
    "EdgeResidual",
    "ExtrapolationPolicy",
    "FieldAlgebra",
    "FieldMappingDefinition",
    "FieldMappingMethod",
    "FrameTransform",
    "IterationSemantics",
    "MappingDiagnostics",
    "MultiphysicsRunRecord",
    "ParticipantSpec",
    "ParticipantStepRecord",
    "PhysicsGraph",
    "PortDefinition",
    "PortDirection",
    "PortKind",
    "PortRef",
    "ReductionOperator",
    "RelaxationKind",
    "RelaxationPolicy",
    "ResidualNorm",
    "TimePolicy",
    "TransferMeasure",
    "WindowOutcome",
]
