"""Generic multiphysics execution runtime."""

from .admission import (
    MULTIPHYSICS_EXECUTION_ADMISSION_SCHEMA,
    MultiphysicsExecutionAdmission,
    admit_multiphysics_execution,
)
from .convergence import ResidualCalculator
from .error import CouplingErrorBudget, CouplingErrorContribution
from .external import (
    ExternalProviderIdentity,
    ExternalSnapshot,
    ExternalSolverParticipant,
    ExternalSolverSession,
)
from .factory import (
    ParticipantFactory,
    ParticipantFactoryCoverage,
    ParticipantFactoryDeclaration,
    ParticipantFactoryRegistry,
)
from .mapping import FieldMapper, FieldMappingResult, StructuredFieldMapper
from .participant import (
    AdvanceRequest,
    AdvanceResult,
    CallbackParticipant,
    CouplingValue,
    ExecutableParticipant,
    InitializationResult,
    InitialStateDefinition,
    InitialStateReceipt,
    InitialStateValue,
    OperatingConditionDefinition,
    OperatingConditionValue,
    ParameterDefinition,
    ParameterValue,
    ParticipantEvent,
    RuntimeCheckpoint,
    StateVariableValue,
    apply_operating_conditions,
    apply_parameters,
    operating_condition_definitions,
    parameter_definitions,
    public_state,
    state_identity,
    validate_inputs,
    validate_outputs,
    validate_port_value,
    validate_uncertainty,
)
from .relaxation import RelaxationController, relax_uncertainty
from .runtime import MultiphysicsExecutionError, MultiphysicsRuntime
from .transfer import (
    FrameTransform,
    TransferEngine,
    TransferResult,
    combine_fan_in_uncertainty,
)

__all__ = [
    "AdvanceRequest",
    "AdvanceResult",
    "CallbackParticipant",
    "CouplingErrorBudget",
    "CouplingErrorContribution",
    "CouplingValue",
    "ExecutableParticipant",
    "ExternalProviderIdentity",
    "ExternalSnapshot",
    "ExternalSolverParticipant",
    "ExternalSolverSession",
    "FieldMapper",
    "FieldMappingResult",
    "FrameTransform",
    "InitializationResult",
    "InitialStateDefinition",
    "InitialStateReceipt",
    "InitialStateValue",
    "MULTIPHYSICS_EXECUTION_ADMISSION_SCHEMA",
    "OperatingConditionDefinition",
    "OperatingConditionValue",
    "ParameterDefinition",
    "ParameterValue",
    "MultiphysicsExecutionAdmission",
    "MultiphysicsExecutionError",
    "MultiphysicsRuntime",
    "ParticipantEvent",
    "ParticipantFactory",
    "ParticipantFactoryCoverage",
    "ParticipantFactoryDeclaration",
    "ParticipantFactoryRegistry",
    "RelaxationController",
    "ResidualCalculator",
    "RuntimeCheckpoint",
    "StateVariableValue",
    "StructuredFieldMapper",
    "TransferEngine",
    "TransferResult",
    "admit_multiphysics_execution",
    "apply_operating_conditions",
    "apply_parameters",
    "combine_fan_in_uncertainty",
    "operating_condition_definitions",
    "parameter_definitions",
    "public_state",
    "relax_uncertainty",
    "state_identity",
    "validate_inputs",
    "validate_outputs",
    "validate_port_value",
    "validate_uncertainty",
]
