"""Domain-neutral design and discovery representation contracts."""

from .archives import ParetoArchive, ScopedEliteArchive, dominates
from .candidate import DesignCandidate, DesignCandidateReference
from .evaluation import (
    DesignEvaluation,
    DesignEvaluationReference,
    FidelitySelection,
    ProjectedObjective,
    ResultBinding,
    SelectionEligibility,
    project_objectives,
    require_result_binding,
)
from .fidelity import FidelityLadder, FidelityRung
from .generation import (
    GENERATION_BINDING_METADATA_KEY,
    CandidateGenerationBatch,
    CandidateGenerationPlan,
    CandidateProposal,
    GenerationStrategy,
    ProposalDecision,
    ProposalGate,
    ProposalRejection,
    TwinMaterializer,
    assignment_digest,
    bind_generation_to_twin,
    generate_initial_population,
    generation_binding_payload,
    validate_generation_binding,
    validate_twin_generation_binding,
)
from .memory import (
    AssessmentContext,
    DesignMemoryEntry,
    DesignMemoryLayerA,
    DesignMemoryPolicy,
    DesignMemoryRecord,
    DesignMemoryScope,
    EntryClassification,
    ExplicitRetention,
    RetentionReason,
    classify_memory,
    compare_entries,
    merge_layer_a_records,
    pareto_member_identities,
    reason_overlaps,
    verify_layer_a_attribution,
)
from .population import DesignPopulation
from .sampling import MixedVariableSampler
from .space import DesignSpace, DesignSpaceReference

__all__ = [
    "AssessmentContext",
    "GENERATION_BINDING_METADATA_KEY",
    "CandidateGenerationBatch",
    "CandidateGenerationPlan",
    "CandidateProposal",
    "DesignCandidate",
    "DesignCandidateReference",
    "DesignEvaluation",
    "DesignEvaluationReference",
    "DesignMemoryEntry",
    "DesignMemoryLayerA",
    "DesignMemoryPolicy",
    "DesignMemoryRecord",
    "DesignMemoryScope",
    "DesignPopulation",
    "DesignSpace",
    "DesignSpaceReference",
    "EntryClassification",
    "ExplicitRetention",
    "FidelityLadder",
    "FidelityRung",
    "FidelitySelection",
    "GenerationStrategy",
    "MixedVariableSampler",
    "ParetoArchive",
    "ProjectedObjective",
    "ProposalDecision",
    "ProposalGate",
    "ProposalRejection",
    "RetentionReason",
    "ResultBinding",
    "ScopedEliteArchive",
    "SelectionEligibility",
    "TwinMaterializer",
    "assignment_digest",
    "bind_generation_to_twin",
    "classify_memory",
    "compare_entries",
    "dominates",
    "generate_initial_population",
    "generation_binding_payload",
    "merge_layer_a_records",
    "pareto_member_identities",
    "project_objectives",
    "reason_overlaps",
    "require_result_binding",
    "validate_generation_binding",
    "validate_twin_generation_binding",
    "verify_layer_a_attribution",
]
