"""Electro-thermal system pack — cross-domain composition, no domain physics.

A *system* pack, not a domain pack. It composes the electrical, material and
thermal packs and owns no physics of its own, which is the only place
cross-domain wiring is allowed to live: a domain module that orchestrated the
system graph would have to know about the other domains.
"""

from .resistor_body import (
    DEPENDENCY_HEAT,
    DEPENDENCY_RESISTANCE,
    DEPENDENCY_TEMPERATURE,
    ElectroThermalResistor,
    OpenLoopPass,
    build_electrical_problem,
    build_twin,
    candidate_sources,
    electrothermal_dependencies,
    electrothermal_problems,
    run_open_loop_pass,
)
from .coupled import (
    COUPLED_ITERATION_SCHEMA,
    COUPLED_RUN_SCHEMA,
    FIXED_POINT_PLAN_SCHEMA,
    TORN_ENDPOINT_SCHEMA,
    CoupledElectroThermalSystem,
    CoupledIteration,
    CoupledRun,
    CoupledStage,
    CouplingOutcome,
    FixedPointCouplingPlan,
    TornEndpoint,
    build_coupled_twin,
    coupled_dependencies,
    coupled_problems,
    cycle_edges,
    execution_order,
    is_ratio_scale,
    edge_key,
    nominal_plan,
    shares_origin,
    stage_problems,
    run_fixed_point,
    run_fixed_point_coupling,
)

__all__ = [
    "COUPLED_ITERATION_SCHEMA",
    "COUPLED_RUN_SCHEMA",
    "CoupledElectroThermalSystem",
    "CoupledIteration",
    "CoupledRun",
    "CoupledStage",
    "CouplingOutcome",
    "DEPENDENCY_HEAT",
    "DEPENDENCY_RESISTANCE",
    "DEPENDENCY_TEMPERATURE",
    "ElectroThermalResistor",
    "FIXED_POINT_PLAN_SCHEMA",
    "FixedPointCouplingPlan",
    "OpenLoopPass",
    "TORN_ENDPOINT_SCHEMA",
    "TornEndpoint",
    "build_coupled_twin",
    "build_electrical_problem",
    "build_twin",
    "candidate_sources",
    "coupled_dependencies",
    "coupled_problems",
    "cycle_edges",
    "edge_key",
    "electrothermal_dependencies",
    "electrothermal_problems",
    "execution_order",
    "is_ratio_scale",
    "nominal_plan",
    "run_fixed_point",
    "run_fixed_point_coupling",
    "run_open_loop_pass",
    "shares_origin",
    "stage_problems",
]
